---
- name: deno role
  tags:
    - deno
  block:

  # assert
  - name: Assertions for deno role
    ansible.builtin.assert:
      that:
      - deno_user != None

  # apt install
  - name: Apt install unzip curl
    become: true
    ansible.builtin.apt:
      state: present
      name: 
      - unzip
      - curl

  # normal user
  - when: deno_user != "root"
    block:

    # install
    - when: deno_state == "present"
      block:

      # check if deno exec is already there
      - name: Check {{ deno_path_exec_user }}
        become: true
        ansible.builtin.stat:
          path: "{{ deno_path_exec_user }}"
        register: __deno_path_exec_user

      # if not install deno
      - when: not __deno_path_exec_user.stat.exists
        block:

        # run script
        - name: Copy and run {{ deno_install_script }}
          become: true
          become_user: "{{ deno_user }}"
          ansible.builtin.script:
            cmd: "{{ deno_install_script }} --yes"

    # reinstall
    - when: deno_state == "reinstall"
      block:

      - name: Copy and run {{ deno_install_script }}
        become: true
        become_user: "{{ deno_user }}"
        ansible.builtin.script:
          cmd: "{{ deno_install_script }} --yes"

    # remove
    - when: deno_state == "absent"
      block:
    
      - name: Remove {{ deno_path_exec_user }}
        become: true
        ignore_errors: true
        failed_when: false
        ansible.builtin.file:
          path: "{{ deno_path_exec_user }}"
          state: absent

  # root user
  - when: deno_user == "root"
    block:

    # check if deno exec is already there
    - name: Check {{ deno_path_exec_root }}
      become: true
      become_user: root
      ansible.builtin.stat:
        path: "{{ deno_path_exec_root }}"
      register: __deno_path_exec_root

    # if not install deno
    - when: not __deno_path_exec_root.stat.exists
      block:

      - name: Copy and run {{ deno_install_script }}
        become: true
        become_user: root
        ansible.builtin.script:
          cmd: "{{ deno_install_script }} --yes"

    # reinstall
    - when: deno_state == "reinstall"
      block:

      - name: Copy and run {{ deno_install_script }}
        become: true
        become_user: "{{ deno_user }}"
        ansible.builtin.script:
          cmd: "{{ deno_install_script }} --yes"

    # remove
    - when: deno_state == "absent"
      block:
    
      - name: Remove {{ deno_path_exec_root }}
        become: true
        ignore_errors: true
        failed_when: false
        ansible.builtin.file:
          path: "{{ deno_path_exec_root }}"
          state: absent